# syntax=docker/dockerfile:1

FROM ubuntu:noble

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        openssh-server \
        sudo \
        locales \
        iproute2 \
        iputils-ping \
        iputils-tracepath \
        inotify-tools \
        readline-common \
        isc-dhcp-client \
    && \
    locale-gen en_US.UTF-8 && \
    mkdir -p /var/run/sshd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    userdel -r ubuntu || true


COPY entrypoint-ssh.sh /usr/bin/entrypoint-ssh
RUN chmod +x /usr/bin/entrypoint-ssh

EXPOSE 22/tcp
ENTRYPOINT ["/usr/bin/entrypoint-ssh"]
